GET http://localhost:8080/cart/ansley

###
POST http://localhost:8080/cart/ansley/add/need
Content-Type: application/json

{
    "name":"Chairs",
    "cost":0.0,
    "currentQuantity":87,
    "type":"plastic"
}

###
POST http://localhost:8080/cart/ansley/checkout

###
GET http://localhost:8080/needs/Chairs
